UI/seller/guide page
kredo-school/16th_rankshty pull request #15
Opened 2024-01-17 22:52 UTC by AYAszk

[UI/seller/guidepage] - Added guidepage.blade.php

2024-01-18 13:13 UTC, Ditzler01 requested changes
Please review my comments. You can reply to each comment here in GitHub.
If you have questions regarding to my comments, please reach out to me in slack.

2024-01-18 13:13 UTC, Ditzler01 commented on composer.json
Did you install a bootstrap library?
Did you run a command like npm install?

2024-01-19 00:56 UTC, AYAszk commented on routes/web.php
> +Route::get('/buyers/help', [BuyerController::class, 'help'])->name('help');
I have a question. Are you suggesting that each time I create a new branch, I should commit with only the route name written in web.php?

2024-01-19 01:17 UTC, AYAszk commented on composer.json
Yes, I have already done it.

2024-01-19 01:34 UTC, AYAszk commented on routes/web.php
> +Route::get('/buyers/help', [BuyerController::class, 'help'])->name('help');
I may have resolved it. It seems conflicts occurred, so it's okay to have just one route name, isn't it?

2024-01-20 02:22 UTC, Ditzler01 approved these changes

2024-01-20 05:13 UTC, merged